# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

# output_dir: ./ # Not needed
# output_dir: /home/cine/Documents/tune/lora_single_device_output/Llama-2-7b-hf/epoch_0

checkpoint_dir: /home/cine/Documents/tune/models/Llama-3.2-3B-Instruct
output_dir : /home/cine/Documents/tune/models/torchtune/llama3_2_3B/lora_single_device/eval_output_o

# Model Arguments
model:
  # _component_: torchtune.models.llama2.llama2_7b
  # Notice that we don't pass the lora model. We are using the merged weights,
  _component_: torchtune.models.llama3_2.llama3_2_3b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  # checkpoint_dir: /tmp/Llama-2-7b-hf
  # checkpoint_files: [
  #   pytorch_model-00001-of-00002.bin,
  #   pytorch_model-00002-of-00002.bin,
  # ]
  checkpoint_dir: ${checkpoint_dir}
  checkpoint_files: [
      model-00001-of-00002.safetensors,
      model-00002-of-00002.safetensors,
  ]
  output_dir: ${output_dir}
  # model_type: LLAMA2
  model_type: LLAMA3_2

# Tokenizer
tokenizer:
  # _component_: torchtune.models.llama2.llama2_tokenizer
  # path: /tmp/Llama-2-7b-hf/tokenizer.model
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${checkpoint_dir}/original/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
