# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# output_dir: ./ # Not needed
checkpoint_dir: /home/cine/Documents/tune/models/torchtune/llama3_2_3B/lora_single_device/epoch_1
output_dir : /home/cine/Documents/tune/models/torchtune/llama3_2_3B/lora_single_device/eval_output

# Model Arguments
model:
  # _component_: torchtune.models.llama2.llama2_7b
  # Notice that we don't pass the lora model. We are using the merged weights,
  _component_: torchtune.models.llama3_2.llama3_2_3b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  # checkpoint_dir: /tmp/Llama-2-7b-hf
  # checkpoint_files: [
  #   pytorch_model-00001-of-00002.bin,
  #   pytorch_model-00002-of-00002.bin,
  # ]
  checkpoint_dir: ${checkpoint_dir}
  checkpoint_files: [
      ft-model-00001-of-00002.safetensors,
      ft-model-00002-of-00002.safetensors,
  ]
  output_dir: ${output_dir}
  # model_type: LLAMA2
  model_type: LLAMA3_2

# Tokenizer
tokenizer:
  # _component_: torchtune.models.llama2.llama2_tokenizer
  # path: /tmp/Llama-2-7b-hf/tokenizer.model
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${checkpoint_dir}/original/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# Generation arguments; defaults taken from gpt-fast
prompt:
  system: null
  user: "Tell me a joke. "
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

enable_kv_cache: True

quantizer: null
